[NPT-536] App compilation failes
When you try to build generated app through nexus cli. It failes because of an old version of Go.
```
/go/pkg/mod/k8s.io/client-go@v0.25.2/third_party/forked/golang/template/exec.go:42:22: undefined: reflect.PointerTo
note: module requires Go 1.19
# k8s.io/apimachinery/third_party/forked/golang/json
/go/pkg/mod/k8s.io/apimachinery@v0.25.2/third_party/forked/golang/json/fields.go:31:17: undefined: reflect.Pointer
/go/pkg/mod/k8s.io/apimachinery@v0.25.2/third_party/forked/golang/json/fields.go:186:40: undefined: reflect.Pointer
note: module requires Go 1.19
# k8s.io/apimachinery/pkg/util/diff
/go/pkg/mod/k8s.io/apimachinery@v0.25.2/pkg/util/diff/diff.go:138:28: undefined: reflect.Pointer
note: module requires Go 1.19
make: *** [Makefile:154: go_get] Error 2
make: *** [Makefile:181: build] Error 2
```
Bump app templates version to 0.0.10

See merge request nsx-allspark_users/nexus-sdk/cli!134